#!/bin/bash' >> /etc/update-motd.d/20-raspberry-bitcoin
ram_total=\u0024(free -m | grep Mem | awk '{ print \u00242 }')
ram_total=\u0024(free -m | grep Mem | awk '{ print \u00242 }')
ram_avail=\u0024(free -m | grep Mem | awk '{ print \u00247 }')
ram_used=\u0024(free -m | grep Mem | awk '{ print \u00243 }')
ram_Xused=\u0024(echo \u0024{ram_used} \u0024{ram_total}| awk '{print \u00241 / \u00242 *100}' | sed 's/\.[^[:blank:]]*//')
hdd_total=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00242 }')
hdd_free=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00244 }')
hdd_used=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00243 }')
hdd_Xused=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00245 }')
ram_swap=\u0024(free -m | grep Swap | awk '{ print \u00243 }')
external_storage=\u0024(df -h | grep '/dev/sd')
if [ ! -z "\u0024{external_storage}" ]; then
external_total=\u0024(echo \u0024{external_storage} | awk '{ print \u00242 }')
external_avail=\u0024(echo \u0024{external_storage} | awk '{ print \u00243 }')
external_Xused=\u0024(df -h | grep "/dev/sd" | awk \u0027{print\u00245}\u0027)
external_info="EXTERNAL STORAGE: \u0024{BOLD}\u0024{external_avail} / \u0024{external_total} \u0024{external_Xused} \u0024{RESET_STYLE}"
else
external_info=\u0024(echo "EXTERNAL STORAGE: N/A ")
fi
swap_check=\u0024(free -mh | grep -i swap | awk '{print substr(\u00242, 1,1)}')
swap_memory=\u0024(free -mh | grep -i swap)
swap_total=\u0024(echo \u0024{swap_memory} | awk '{print substr(\u00242, 1, length(\u00242) - 2)}')
if [ "\u0024{swap_check}" != "0" ]; then
swap_info="SWAP: \u0024{BOLD}\u0024{ram_swap}M / \u0024{swap_total}G\u0024{RESET_STYLE}"
else
swap_info="\u0024(tput -T xterm setaf 2)SWAP: N/A"
fi 
GEOLOC="\u0024(curl https://extreme-ip-lookup.com/json/?key=ACJdcEKqljZrmlXp1GZA)"
geoloc=\u0022\u0024(echo \u0024{GEOLOC} | jq -r \u0027.country\u0027 | tr \u0027[:lower:]\u0027 \u0027[:upper:]\u0027)\u0022
geoloc=\u0022\u0024(echo \u0024{GEOLOC} | jq -r \u0027.country\u0027 | tr \u0027[:lower:]\u0027 \u0027[:upper:]\u0027)\u0022
RPI=\u0022\u0024(tr -d '\0' < /proc/device-tree/model)\u0022  
rpimod=\u0022\u0024(echo \u0024{RPI} | tr '[:lower:]' '[:upper:]')\u0022
TIME=\u0022\u0024(uptime | sed 's/.*up \([^,]*\), .*/\1/')\u0022
uptime="\u0024(echo \u0024{TIME})"
GHZ=\u0022\u0024(vcgencmd measure_clock arm | awk ' BEGIN { FS=\u0022=\u0022 } ; { printf(\u0022%.1fGHz\u005C\u006E\u0022, \u00242 / 1000000000) } ')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin  
ghz="\u0024(echo \u0024{GHZ})"' >> /etc/update-motd.d/20-raspberry-bitcoin
VOLTS=\u0022\u0024(vcgencmd measure_volts \u0024id | awk '{print substr(\u00240, 6, length(\u00240) - 9)} ')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
volts="\u0024(echo \u0024{VOLTS})"' >> /etc/update-motd.d/20-raspberry-bitcoin
PUBIP="\u0024(curl ifconfig.co)"' >> /etc/update-motd.d/20-raspberry-bitcoin  
pubip="\u0024(echo \u0024{PUBIP})"' >> /etc/update-motd.d/20-raspberry-bitcoin
IP="\u0024(hostname -I)"' >> /etc/update-motd.d/20-raspberry-bitcoin
ip="\u0024(echo \u0024{IP})"' >> /etc/update-motd.d/20-raspberry-bitcoin
TEMPCPU=\u0022\u0024(awk '{printf(\u0022\u005C\u006E%.1f°C\u005C\u006E\u005C\u006E\u0022,\u00241/1e3)}' /sys/class/thermal/thermal_zone0/temp)\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin  
temp="\u0024(echo \u0024{TEMPCPU})"' >> /etc/update-motd.d/20-raspberry-bitcoin
CPUUSED=\u0022\u0024(vmstat 1 2 | tail -1 | awk '{print \u002413}')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
cpuused=\u0022\u0024(echo \u0024{CPUUSED})\u0022' >> /etc/update-motd.d/20-raspberry-bitcoin
data_dir="/mnt/hdd/bitcoin"' >> /etc/update-motd.d/20-raspberry-bitcoin    
btc_path=\u0024(command -v bitcoin-cli)" >> /etc/update-motd.d/20-raspberry-bitcoin
if [ ! -z \u0024{btc_path} ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line1="BITCOIN CORE"' >> /etc/update-motd.d/20-raspberry-bitcoin
BLOCKCHAIN_INFO="\u0024(bitcoin-cli -datadir=\u0024{data_dir} getblockchaininfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin  
chain=\u0022\u0024(echo \u0024{BLOCKCHAIN_INFO} | jq -r '.chain' | tr '[:lower:]' '[:upper:]')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
if [ ! -z \u0024chain ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
chain="\u0024{chain}NET"' >> /etc/update-motd.d/20-raspberry-bitcoin
fi" >> /etc/update-motd.d/20-raspberry-bitcoin  
blocks=\u0022\u0024(echo \u0024{BLOCKCHAIN_INFO} | jq -r '.blocks')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
progress=\u0022\u0024(echo \u0024{BLOCKCHAIN_INFO} | jq -r '.verificationprogress')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
percentage=\u0024(printf \u0022%.2f%%\u0022 \u0022\u0024(echo \u0024progress | awk '{print 100 * \u0024\1}')\u0022)" >> /etc/update-motd.d/20-raspberry-bitcoin
if [ -n \u0024percentage ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin 
l2_extra="sync progress: \u0024{percentage}"' >> /etc/update-motd.d/20-raspberry-bitcoin
fi" >> /etc/update-motd.d/20-raspberry-bitcoin
PEER_INFO="\u0024(bitcoin-cli -datadir=\u0024{data_dir} getpeerinfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
peers_count=\u0024(echo \u0024{PEER_INFO} | jq 'length')" >> /etc/update-motd.d/20-raspberry-bitcoin 
balance="\u0024(bitcoin-cli -datadir=\u0024data_dir getbalance 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
re='[+-]?([0-9]*[.])?[0-9]+\u0024'" >> /etc/update-motd.d/20-raspberry-bitcoin
if ! [[ \u0024balance =~ \u0024re ]]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
balance="\u0024(tput -T xterm setaf 2)N/A"' >> /etc/update-motd.d/20-raspberry-bitcoin  
fi" >> /etc/update-motd.d/20-raspberry-bitcoin
NETWORK_INFO="\u0024(bitcoin-cli -datadir=\u0024{data_dir} getnetworkinfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
networks="\u0024(echo \u0024{NETWORK_INFO} | jq -r \u0027[.localaddresses[] | [.address, .port|tostring] | join(":")] | join("\t")\u0027)"' >> /etc/update-motd.d/20-raspberry-bitcoin
version="\u0024(echo \u0024{NETWORK_INFO} | jq -r \u0027.subversion\u0027 | grep -Po \u0027((\d+\.?){3})\u0027)"' >> /etc/update-motd.d/20-raspberry-bitcoin
MEMPOOL_INFO="\\u0024(bitcoin-cli -datadir=\u0024{data_dir} getmempoolinfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
mempool="\u0024(echo \u0024{MEMPOOL_INFO} | jq -r \u0022.size\u0022 | xargs)\u0022' >> /etc/update-motd.d/20-raspberry-bitcoin
else" >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line2="\u0024(tput -T xterm setaf 1)NOT RUNNING"' >> /etc/update-motd.d/20-raspberry-bitcoin  
fi" >> /etc/update-motd.d/20-raspberry-bitcoin
if [ ! -z "\u0024{btc_line1}" ] && [ ! -z \u0024{chain} ]; then' >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line1="\u0024{btc_line1} (V\u0024{version}, \u0024{chain})"' >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line2="PEERS: \u0024{peers_count} / ON BLOCK: \u0024{blocks} SYNC: \u0024{percentage}"' >> /etc/update-motd.d/20-raspberry-bitcoin 
btc_line3="BALANCE: \u0024{balance} / MEMPOOL TRANSACTIONS: \u0024{mempool}"' >> /etc/update-motd.d/20-raspberry-bitcoin
if [ ! -z "\u0024{networks}" ]; then' >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line4="PUBLIC IP / \u0024{networks}"' >> /etc/update-motd.d/20-raspberry-bitcoin
fi" >> /etc/update-motd.d/20-raspberry-bitcoin  
else" >> /etc/update-motd.d/20-raspberry-bitcoin
ps cax | grep bitcoind >/dev/null 2>&1" >> /etc/update-motd.d/20-raspberry-bitcoin
if [ \u0024? -eq 0 ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line2="\u0024(tput -T xterm setaf 1)BTC CORE STARTING"' >> /etc/update-motd.d/20-raspberry-bitcoin 
else" >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line2="\u0024(tput -T xterm setaf 1)BTC CORE NOT RUNNING"' >> /etc/update-motd.d/20-raspberry-bitcoin
fi" >> /etc/update-motd.d/20-raspberry-bitcoin
fi" >> /etc/update-motd.d/20-raspberry-bitcoin  
Ver=\u0022\u0024(sudo -u pi ./bfgminer/bfgminer --version | grep -n 4 | awk '{ print \u00242 }' | sed -e 's/\-[^\.]*\u0024//')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
ps cax | grep bfgminer >/dev/null 2>&1" >> /etc/update-motd.d/20-raspberry-bitcoin
if [ \u0024? -eq 0 ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line5="\u0024(tput -T xterm setaf 1)BFGMINER \u0024{Ver}"' >> /etc/update-motd.d/20-raspberry-bitcoin  
else" >> /etc/update-motd.d/20-raspberry-bitcoin
btc_line5="\u0024(tput -T xterm setaf 1)BFGMINER NOT RUNNING"' >> /etc/update-motd.d/20-raspberry-bitcoin
fi" >> /etc/update-motd.d/20-raspberry-bitcoin
Check1=\u0022\u0024( curl -d '{\u0022addr\u0022:\u00221LdJ4nyxrJqNB1oyr76rYerb2KDZk9wAvo\u0022}' -H 'Authorization: Bearer KR9NNX9cXq9KIiowcoDWaHKHsVakW1ZNoH0zWied5S8' https://www.blockonomics.co/api/balance | sed 's/,.*//' | tr -d '{\u0022response\u0022: [{\u0022confirmed\u0022: ' )\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin 
Check="\u0024(echo \u0024{Check1:0:3}.\u0024{Check1:3:3}) BTC"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "\u0024(tput -T xterm setaf 2)' >> /etc/update-motd.d/20-raspberry-bitcoin
         ___ ___________" >> /etc/update-motd.d/20-raspberry-bitcoin
        / _ )_  __/ ___/     \u0024(tput -T xterm setaf 1)\u0024{rpimod}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin 
       / _  |/ / / /__       \u0024(tput -T xterm setaf 2)CPU: \u0024{temp}\u0024(tput -T xterm setaf 2)\u0024(tput -T xterm setaf 2) \u0024{ghz} \u0024{volts}V \u0024{cpuused} % UPTIME: \u0024{uptime}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
      /____//_/  \___/_____  \u0024(tput -T xterm setaf 2)MEM: \u0024{ram_used}M/\u0024{ram_total}M \u0024{ram_Xused}% SD STORAGE: \u0024{hdd_used}/\u0024{hdd_total} \u0024{hdd_Xused}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
     / /  / __ \/_  __/ __ \ \u0024(tput -T xterm setaf 2)\u0024{external_info}\u0024{swap_info}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
    / /__/ /_/ / / / / /_/ / \u0024(tput -T xterm setaf 2)IP'S: \u0024{ip} / \u0024{pubip}  \u0024{geoloc}" >> /etc/update-motd.d/20-raspberry-bitcoin 
   /____/\____/_/_/  \____/  \u0024(tput -T xterm setaf 1)\u0024{btc_line1}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
  / _ \/ _ \/  _/            \u0024(tput -T xterm setaf 2)\u0024{btc_line2}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
 / , _/ ___// /              \u0024(tput -T xterm setaf 2)\u0024{btc_line3}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
/_/|_/_/  /___/              \u0024(tput -T xterm setaf 2)\u0024{btc_line5}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin 
                             \u0024(tput -T xterm setaf 2)\u0024{btc_line4}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
                             \u0024(tput -T xterm setaf 2)\u0024{Check} \u0024{Check1} SATS\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
                             \u0024(tput -T xterm setaf 2)\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
                             \u0024(tput -T xterm sgr0)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo \u0024(tput -T xterm setaf 7)WEB\u0024(tput -T xterm setaf 7)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo \u0024(tput -T xterm setaf 7)To open Web Monitor goto: http://\u0024{ip}/index.php\u0024(tput -T xterm setaf 7)" >> /etc/update-motd.d/20-raspberry-bitcoin


chmod +x /etc/update-motd.d/20-raspberry-bitcoin
chmod -x /etc/update-motd.d/30-swap-warning
run-parts --lsbsysinit /etc/update-motd.d
