#!/bin/bash' >> /etc/update-motd.d/20-raspberry-bitcoin
ram_total=\u0024(free -m | grep Mem | awk '{ print \u00242 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
ram_total=\u0024(free -m | grep Mem | awk '{ print \u00242 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
ram_avail=\u0024(free -m | grep Mem | awk '{ print \u00247 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
ram_used=\u0024(free -m | grep Mem | awk '{ print \u00243 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
ram_Xused=\u0024(echo \u0024{ram_used} \u0024{ram_total}| awk '{print \u00241 / \u00242 *100}' | sed 's/\.[^[:blank:]]*//')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "hdd_total=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00242 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "hdd_free=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00244 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "hdd_used=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00243 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "hdd_Xused=\u0024(df -h | grep '\u002F\u0024' | awk '{ print \u00245 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "ram_swap=\u0024(free -m | grep Swap | awk '{ print \u00243 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "external_storage=\u0024(df -h | grep '/dev/sd')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'if [ ! -z "\u0024{external_storage}" ]; then' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "external_total=\u0024(echo \u0024{external_storage} | awk '{ print \u00242 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "external_avail=\u0024(echo \u0024{external_storage} | awk '{ print \u00243 }')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'external_Xused=\u0024(df -h | grep "/dev/sd" | awk \u0027{print\u00245}\u0027)' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'external_info="EXTERNAL STORAGE: \u0024{BOLD}\u0024{external_avail} / \u0024{external_total} \u0024{external_Xused} \u0024{RESET_STYLE}"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "else" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'external_info=\u0024(echo "EXTERNAL STORAGE: N/A ")' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "swap_check=\u0024(free -mh | grep -i swap | awk '{print substr(\u00242, 1,1)}')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "swap_memory=\u0024(free -mh | grep -i swap)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "swap_total=\u0024(echo \u0024{swap_memory} | awk '{print substr(\u00242, 1, length(\u00242) - 2)}')" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'if [ "\u0024{swap_check}" != "0" ]; then' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'swap_info="SWAP: \u0024{BOLD}\u0024{ram_swap}M / \u0024{swap_total}G\u0024{RESET_STYLE}"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "else" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'swap_info="\u0024(tput -T xterm setaf 2)SWAP: N/A"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e 'GEOLOC="\u0024(curl https://extreme-ip-lookup.com/json/?key=ACJdcEKqljZrmlXp1GZA)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'geoloc=\u0022\u0024(echo \u0024{GEOLOC} | jq -r \u0027.country\u0027 | tr \u0027[:lower:]\u0027 \u0027[:upper:]\u0027)\u0022' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "geoloc=\u0022\u0024(echo \u0024{GEOLOC} | jq -r \u0027.country\u0027 | tr \u0027[:lower:]\u0027 \u0027[:upper:]\u0027)\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "RPI=\u0022\u0024(tr -d '\0' < /proc/device-tree/model)\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e "rpimod=\u0022\u0024(echo \u0024{RPI} | tr '[:lower:]' '[:upper:]')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "TIME=\u0022\u0024(uptime | sed 's/.*up \([^,]*\), .*/\1/')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'uptime="\u0024(echo \u0024{TIME})"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "GHZ=\u0022\u0024(vcgencmd measure_clock arm | awk ' BEGIN { FS=\u0022=\u0022 } ; { printf(\u0022%.1fGHz\u005C\u006E\u0022, \u00242 / 1000000000) } ')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e 'ghz="\u0024(echo \u0024{GHZ})"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "VOLTS=\u0022\u0024(vcgencmd measure_volts \u0024id | awk '{print substr(\u00240, 6, length(\u00240) - 9)} ')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'volts="\u0024(echo \u0024{VOLTS})"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'PUBIP="\u0024(curl ifconfig.co)"' >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e 'pubip="\u0024(echo \u0024{PUBIP})"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'IP="\u0024(hostname -I)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'ip="\u0024(echo \u0024{IP})"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "TEMPCPU=\u0022\u0024(awk '{printf(\u0022\u005C\u006E%.1f°C\u005C\u006E\u005C\u006E\u0022,\u00241/1e3)}' /sys/class/thermal/thermal_zone0/temp)\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e 'temp="\u0024(echo \u0024{TEMPCPU})"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "CPUUSED=\u0022\u0024(vmstat 1 2 | tail -1 | awk '{print \u002413}')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'cpuused=\u0022\u0024(echo \u0024{CPUUSED})\u0022' >> /etc/update-motd.d/20-raspberry-bitcoin
echo 'data_dir="/mnt/hdd/bitcoin"' >> /etc/update-motd.d/20-raspberry-bitcoin    
echo -e "btc_path=\u0024(command -v bitcoin-cli)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "if [ ! -z \u0024{btc_path} ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
echo 'btc_line1="BITCOIN CORE"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'BLOCKCHAIN_INFO="\u0024(bitcoin-cli -datadir=\u0024{data_dir} getblockchaininfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e "chain=\u0022\u0024(echo \u0024{BLOCKCHAIN_INFO} | jq -r '.chain' | tr '[:lower:]' '[:upper:]')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "if [ ! -z \u0024chain ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'chain="\u0024{chain}NET"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e "blocks=\u0022\u0024(echo \u0024{BLOCKCHAIN_INFO} | jq -r '.blocks')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "progress=\u0022\u0024(echo \u0024{BLOCKCHAIN_INFO} | jq -r '.verificationprogress')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "percentage=\u0024(printf \u0022%.2f%%\u0022 \u0022\u0024(echo \u0024progress | awk '{print 100 * \u0024\1}')\u0022)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "if [ -n \u0024percentage ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin 
echo -e 'l2_extra="sync progress: \u0024{percentage}"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'PEER_INFO="\u0024(bitcoin-cli -datadir=\u0024{data_dir} getpeerinfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "peers_count=\u0024(echo \u0024{PEER_INFO} | jq 'length')" >> /etc/update-motd.d/20-raspberry-bitcoin 
echo -e 'balance="\u0024(bitcoin-cli -datadir=\u0024data_dir getbalance 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "re='[+-]?([0-9]*[.])?[0-9]+\u0024'" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "if ! [[ \u0024balance =~ \u0024re ]]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'balance="\u0024(tput -T xterm setaf 2)N/A"' >> /etc/update-motd.d/20-raspberry-bitcoin  
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'NETWORK_INFO="\u0024(bitcoin-cli -datadir=\u0024{data_dir} getnetworkinfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'networks="\u0024(echo \u0024{NETWORK_INFO} | jq -r \u0027[.localaddresses[] | [.address, .port|tostring] | join(":")] | join("\t")\u0027)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'version="\u0024(echo \u0024{NETWORK_INFO} | jq -r \u0027.subversion\u0027 | grep -Po \u0027((\d+\.?){3})\u0027)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'MEMPOOL_INFO="\\u0024(bitcoin-cli -datadir=\u0024{data_dir} getmempoolinfo 2> /dev/null)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'mempool="\u0024(echo \u0024{MEMPOOL_INFO} | jq -r \u0022.size\u0022 | xargs)\u0022' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "else" >> /etc/update-motd.d/20-raspberry-bitcoin
echo 'btc_line2="\u0024(tput -T xterm setaf 1)NOT RUNNING"' >> /etc/update-motd.d/20-raspberry-bitcoin  
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'if [ ! -z "\u0024{btc_line1}" ] && [ ! -z \u0024{chain} ]; then' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'btc_line1="\u0024{btc_line1} (V\u0024{version}, \u0024{chain})"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'btc_line2="PEERS: \u0024{peers_count} / ON BLOCK: \u0024{blocks} SYNC: \u0024{percentage}"' >> /etc/update-motd.d/20-raspberry-bitcoin 
echo -e 'btc_line3="BALANCE: \u0024{balance} / MEMPOOL TRANSACTIONS: \u0024{mempool}"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'if [ ! -z "\u0024{networks}" ]; then' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'btc_line4="PUBLIC IP / \u0024{networks}"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin  
echo "else" >> /etc/update-motd.d/20-raspberry-bitcoin
echo "ps cax | grep bitcoind >/dev/null 2>&1" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "if [ \u0024? -eq 0 ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'btc_line2="\u0024(tput -T xterm setaf 1)BTC CORE STARTING"' >> /etc/update-motd.d/20-raspberry-bitcoin 
echo "else" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'btc_line2="\u0024(tput -T xterm setaf 1)BTC CORE NOT RUNNING"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin  
echo -e "Ver=\u0022\u0024(sudo -u pi ./bfgminer/bfgminer --version | grep -n 4 | awk '{ print \u00242 }' | sed -e 's/\-[^\.]*\u0024//')\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin
echo "ps cax | grep bfgminer >/dev/null 2>&1" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "if [ \u0024? -eq 0 ]; then" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'btc_line5="\u0024(tput -T xterm setaf 1)BFGMINER \u0024{Ver}"' >> /etc/update-motd.d/20-raspberry-bitcoin  
echo "else" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'btc_line5="\u0024(tput -T xterm setaf 1)BFGMINER NOT RUNNING"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "fi" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "Check1=\u0022\u0024( curl -d '{\u0022addr\u0022:\u00221LdJ4nyxrJqNB1oyr76rYerb2KDZk9wAvo\u0022}' -H 'Authorization: Bearer KR9NNX9cXq9KIiowcoDWaHKHsVakW1ZNoH0zWied5S8' https://www.blockonomics.co/api/balance | sed 's/,.*//' | tr -d '{\u0022response\u0022: [{\u0022confirmed\u0022: ' )\u0022" >> /etc/update-motd.d/20-raspberry-bitcoin 
echo -e 'Check="\u0024(echo \u0024{Check1:0:3}.\u0024{Check1:3:3}) BTC"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e 'echo "\u0024(tput -T xterm setaf 2)' >> /etc/update-motd.d/20-raspberry-bitcoin
echo "         ___ ___________" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "        / _ )_  __/ ___/     \u0024(tput -T xterm setaf 1)\u0024{rpimod}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin 
echo -e "       / _  |/ / / /__       \u0024(tput -T xterm setaf 2)CPU: \u0024{temp}\u0024(tput -T xterm setaf 2)\u0024(tput -T xterm setaf 2) \u0024{ghz} \u0024{volts}V \u0024{cpuused} % UPTIME: \u0024{uptime}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "      /____//_/  \___/_____  \u0024(tput -T xterm setaf 2)MEM: \u0024{ram_used}M/\u0024{ram_total}M \u0024{ram_Xused}% SD STORAGE: \u0024{hdd_used}/\u0024{hdd_total} \u0024{hdd_Xused}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "     / /  / __ \/_  __/ __ \ \u0024(tput -T xterm setaf 2)\u0024{external_info}\u0024{swap_info}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "    / /__/ /_/ / / / / /_/ / \u0024(tput -T xterm setaf 2)IP'S: \u0024{ip} / \u0024{pubip}  \u0024{geoloc}" >> /etc/update-motd.d/20-raspberry-bitcoin 
echo -e "   /____/\____/_/_/  \____/  \u0024(tput -T xterm setaf 1)\u0024{btc_line1}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "  / _ \/ _ \/  _/            \u0024(tput -T xterm setaf 2)\u0024{btc_line2}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e " / , _/ ___// /              \u0024(tput -T xterm setaf 2)\u0024{btc_line3}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "/_/|_/_/  /___/              \u0024(tput -T xterm setaf 2)\u0024{btc_line5}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin 
echo -e "                             \u0024(tput -T xterm setaf 2)\u0024{btc_line4}\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "                             \u0024(tput -T xterm setaf 2)\u0024{Check} \u0024{Check1} SATS\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "                             \u0024(tput -T xterm setaf 2)\u0024(tput -T xterm setaf 2)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e '                             \u0024(tput -T xterm sgr0)"' >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "echo \u0024(tput -T xterm setaf 7)WEB\u0024(tput -T xterm setaf 7)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo -e "echo \u0024(tput -T xterm setaf 7)To open Web Monitor goto: http://\u0024{ip}/index.php\u0024(tput -T xterm setaf 7)" >> /etc/update-motd.d/20-raspberry-bitcoin
echo " " >> /etc/update-motd.d/20-raspberry-bitcoin

chmod +x /etc/update-motd.d/20-raspberry-bitcoin
chmod -x /etc/update-motd.d/30-swap-warning
run-parts --lsbsysinit /etc/update-motd.d
