crontab -r
rm /etc/environment
rm /etc/default/locale
touch /etc/default/locale
echo "#  File generated by update-locale"
echo "LANG=en_GB.UTF-8"
sed -i 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/g' /etc/locale.gen
sed -i 's/en_US.UTF-8 UTF-8/# en_US.UTF-8 UTF-8/g' /etc/locale.gen
rm -r /var/www/html/index.php
rm /var/www/html/miner.php
apt purge php7.4 -y
apt purge apache2 -y
rm -r /etc/apache2
rm /usr/share/keyrings/tailscale-archive-keyring.gpg
rm /etc/apt/sources.list.d/tailscale.list
rm /etc/apt/sources.list.d/tailscale.list.save
apt remove apt-transport-https -y
apt purge tailscale -y
swapon --all
apt install dphys-swapfile -y
pip uninstall glances -y
apt purge python3-pip -y
rm /usr/local/bin/speedtest-cli
sed -i 's/#Watchdog On/ /g' /boot/config.txt
sed -i 's/dtparam=watchdog=on/ /g' /boot/config.txt
systemctl stop watchdog
systemctl disable watchdog
rm /etc/watchdog.conf
apt purge watchdog -y
rm /etc/sysctl.d/disable-ipv6.conf
sed -i 's/ipv6.disable=1/ /g' /boot/cmdline.txt
systemctl enable hciuart.service
systemctl enable bluetooth.service
sed -i 's/# Disable Bluetooth/ /g' /boot/config.txt
sed -i 's/dtoverlay=disable-bt/ /g' /boot/config.txt
rm /home/pi/mymacchanger.py
sed -i '1d' /var/spool/cron/root
sed -i '2d' /var/spool/cron/root
sed -i '3d' /var/spool/cron/root
rm -r /var/spool/cron/root
apt purge jq -y
apt purge python3-pip -y
pip uninstall telepot -y
rm -r /home/pi/Bots
systemctl stop bot.service
rm /etc/systemd/system/bot.service
systemctl disable bot.service
systemctl daemon-reload
sed -i '1d' /var/spool/cron/root
sed -i '2d' /var/spool/cron/root
sed -i '3d' /var/spool/cron/root
rm /etc/motd
rm -r /etc/update-motd.d/20-raspberry-bitcoin
rm -r /etc/update-motd.d/10-uname
apt purge jq -y
apt purge python3.9 -y
rm -r /usr/local/lib/python3.9
rm -r /usr/lib/python3
rm -r usr/lib/php
crontab -u pi -r
apt autoremove -y
rm uninstall.sh
