sudo crontab -r
sudo apt purge python-is-python2 -y
sudo rm /etc/environment
sudo rm /etc/default/locale
sudo touch /etc/default/locale
sudo echo "#  File generated by update-locale"
sudo echo "LANG=en_GB.UTF-8"
sudo sed -i 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/g' /etc/locale.gen
sudo sed -i 's/en_US.UTF-8 UTF-8/# en_US.UTF-8 UTF-8/g' /etc/locale.gen
sudo rm -r /var/www/html/index.php
sudo rm -r /var/www/html/miner.php
sudo rm -r /var/www
sudo apt purge php7.4 -y
sudo apt purge apache2 -y
sudo rm -r /etc/apache2
sudo rm /usr/share/keyrings/tailscale-archive-keyring.gpg
sudo rm /etc/apt/sources.list.d/tailscale.list
sudo rm /etc/apt/sources.list.d/tailscale.list.save
sudo apt remove apt-transport-https -y
sudo apt purge tailscale -y
sudo swapon --all
sudo apt install dphys-swapfile -y
sudo pip uninstall glances -y
sudo apt purge python3-pip -y
sudo rm /usr/local/bin/speedtest-cli
sudo sed -i 's/#Watchdog On/ /g' /boot/config.txt
sudo sed -i 's/dtparam=watchdog=on/ /g' /boot/config.txt
sudo systemctl stop watchdog
sudo systemctl disable watchdog
sudo rm /etc/watchdog.conf
sudo apt purge watchdog -y
sudo rm /etc/sysctl.d/disable-ipv6.conf
sudo sed -i 's/ipv6.disable=1/ /g' /boot/cmdline.txt
sudo systemctl enable hciuart.service
sudo systemctl enable bluetooth.service
sudo sed -i 's/# Disable Bluetooth/ /g' /boot/config.txt
sudo sed -i 's/dtoverlay=disable-bt/ /g' /boot/config.txt
sudo rm /home/pi/mymacchanger.py
sudo apt purge jq -y
sudo apt purge python -y
sudo apt purge python3-pip -y
sudo pip uninstall telepot -y
sudo rm -r /home/pi/Bots
sudo systemctl stop bot.service
sudo rm /etc/systemd/system/bot.service
sudo systemctl disable bot.service
sudo systemctl daemon-reload
sudo rm /etc/motd
sudo rm -r /etc/update-motd.d/ssh-welcome
sudo rm -r /etc/update-motd.d/10-uname
sudo apt purge jq -y
sudo apt purge python3.9 -y
sudo rm -r /usr/local/lib/python3.9
sudo rm -r /usr/lib/python3
sudo rm -r /usr/lib/php
sudo rm -r /usr/lib/apache2
sudo rm -r /usr/lib/python2.7
sudo rm -r /usr/lib/python3.9
sudo crontab -u pi -r
sudo apt autoremove -y
sudo apt-get clean
sudo apt-get autoclean
sudo rm uninstall.sh
